export const ROLES = ["ADMIN", "TEAM_LEAD", "EMPLOYEE"] as const;
export type RoleName = (typeof ROLES)[number];

export const PERMISSIONS = [
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.archive",
  "salary.view",
  "salary.update",
  "departments.view",
  "departments.create",
  "departments.update",
  "departments.archive",
  "teams.view",
  "teams.create",
  "teams.update",
  "teams.archive",
  "schedules.view",
  "schedules.create",
  "schedules.update",
  "schedules.archive",
  "appraisals.view",
  "appraisals.create",
  "projects.view",
  "projects.create",
  "projects.update",
  "projects.archive",
  "tasks.view",
  "tasks.create",
  "tasks.update",
  "tasks.assign",
  "time_entries.create",
] as const;
export type PermissionName = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  ADMIN: [
    "employees.view",
    "employees.create",
    "employees.update",
    "employees.archive",
    "salary.view",
    "salary.update",
    "departments.view",
    "departments.create",
    "departments.update",
    "departments.archive",
    "teams.view",
    "teams.create",
    "teams.update",
    "teams.archive",
    "schedules.view",
    "schedules.create",
    "schedules.update",
    "schedules.archive",
    "appraisals.view",
    "appraisals.create",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.archive",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "time_entries.create",
  ],
  TEAM_LEAD: [
    "employees.view",
    "departments.view",
    "teams.view",
    "schedules.view",
    "projects.view",
    "projects.create",
    "projects.update",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "time_entries.create",
  ],
  EMPLOYEE: [
    "employees.view",
    "departments.view",
    "teams.view",
    "schedules.view",
    "projects.view",
    "tasks.view",
    "tasks.update",
    "time_entries.create",
  ],
};
