export const ROLES = ["ADMIN", "TEAM_LEAD", "PROJECT_MANAGER", "EMPLOYEE"] as const;
export type RoleName = (typeof ROLES)[number];

/** Roles that get the team-lead view of dashboards, reports and workload. */
export function isLeadRole(role: string | undefined): boolean {
  return role === "TEAM_LEAD" || role === "PROJECT_MANAGER";
}

export const PERMISSIONS = [
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.archive",
  "employees.delete",
  "salary.view",
  "salary.update",
  "departments.view",
  "departments.create",
  "departments.update",
  "departments.archive",
  "departments.delete",
  "teams.view",
  "teams.create",
  "teams.update",
  "teams.archive",
  "teams.delete",
  "schedules.view",
  "schedules.create",
  "schedules.update",
  "schedules.archive",
  "appraisals.view",
  "appraisals.create",
  "projects.view",
  "projects.create",
  "projects.update",
  "projects.archive",
  "projects.delete",
  "tasks.view",
  "tasks.create",
  "tasks.update",
  "tasks.assign",
  "tasks.delete",
  "time_entries.create",
  "reports.view",
  "roles.assign",
] as const;
export type PermissionName = (typeof PERMISSIONS)[number];

// Team Lead and Project Manager share one permission set. Neither has
// salary.* or appraisals.*, so neither can see or change pay.
const LEAD_PERMISSIONS: PermissionName[] = [
  "employees.view",
  "departments.view",
  "teams.view",
  "schedules.view",
  "projects.view",
  "projects.create",
  "projects.update",
  "tasks.view",
  "tasks.create",
  "tasks.update",
  "tasks.assign",
  "time_entries.create",
  "reports.view",
];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  ADMIN: [
    "employees.view",
    "employees.create",
    "employees.update",
    "employees.archive",
    "employees.delete",
    "salary.view",
    "salary.update",
    "departments.view",
    "departments.create",
    "departments.update",
    "departments.archive",
    "departments.delete",
    "teams.view",
    "teams.create",
    "teams.update",
    "teams.archive",
    "teams.delete",
    "schedules.view",
    "schedules.create",
    "schedules.update",
    "schedules.archive",
    "appraisals.view",
    "appraisals.create",
    "projects.view",
    "projects.create",
    "projects.update",
    "projects.archive",
    "projects.delete",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.delete",
    "time_entries.create",
    "reports.view",
    "roles.assign",
  ],
  TEAM_LEAD: LEAD_PERMISSIONS,
  PROJECT_MANAGER: LEAD_PERMISSIONS,
  EMPLOYEE: [
    "employees.view",
    "departments.view",
    "teams.view",
    "schedules.view",
    "projects.view",
    "tasks.view",
    "tasks.update",
    "time_entries.create",
    "reports.view",
  ],
};
